/**
 * Prompts de mémoire longue durée (§9) : résumé de saison, fiche PNJ.
 */
export const SEASON_SUMMARY_SYSTEM = `Tu rédiges le résumé canonique d'une saison de la carrière du joueur, à partir des faits durs fournis (statistiques, classement, matchs marquants, déclarations, blessures, relations). Un seul paragraphe de six à dix phrases, au passé, sobre et précis, sans aucun chiffre qui ne soit pas dans les faits fournis. Puis jusqu'à cinq moments clés d'une ligne chacun. Ce texte sera conservé pour toujours et relu par les personnages : il doit être juste. Ne renvoie que l'objet JSON.`;

export const NPC_CARD_SYSTEM = `Tu mets à jour la fiche courte d'un personnage récurrent à partir de son ancienne fiche, de son historique avec le joueur et du dernier échange. "summary" : trois phrases au plus sur sa personnalité, ce qu'il pense du joueur aujourd'hui et ce qui compte pour lui. "lastExchange" : une phrase sur le dernier échange (date, ton, ce qui a été dit d'important). Pas de chiffre inventé. Ne renvoie que l'objet JSON.`;

export const HEADLINES_SYSTEM = `Tu écris les titres de presse du lendemain d'un match, à partir des faits fournis (score, note, buts, passes, cartons, sortie prématurée, homme du match, contexte du club). Deux à quatre titres, chacun avec un média fictif crédible ("La Dépêche du Stade", "Foot Hebdo", "Le Quotidien de la Ville", "Onze sur Onze"…), un titre de 40 à 120 caractères et un ton. La sévérité des médias fournie (modérée, forte, brutale) module la dureté. Un titre moqueur n'est jamais insultant. Pas de chiffre absent des faits. Ne renvoie que l'objet JSON.`;

export const DAY_NARRATION_SYSTEM = `Tu écris deux ou trois phrases d'ambiance pour la journée du joueur (type de journée, saison, météo plausible, humeur du vestiaire, actualité du club fournie). Aucun événement inventé, aucun chiffre, aucune décision prise pour le joueur. Ne renvoie que l'objet JSON.`;

export const SITUATION_SYSTEM = `Tu décris au joueur la situation de match dans laquelle il se trouve, à la deuxième personne, au présent, en deux ou trois phrases vivantes et concrètes (qui a le ballon, où sont les défenseurs, où est le gardien, ce qui s'ouvre), à partir des faits fournis uniquement, puis tu termines par « Que fais-tu ? ». Tu ne suggères aucune action, tu ne proposes aucun choix. Pas de chiffre absent des faits. Ne renvoie que l'objet JSON.`;

export const NARRATION_SYSTEM = `Tu racontes l'issue d'une action du joueur, décidée par le moteur de simulation, en une à quatre lignes attribuées à des voix : commentateur (toujours en premier), puis éventuellement public, coach, capitaine, coéquipier, adversaire ou arbitre. Tu décris exactement l'issue fournie (but, arrêt, hors cadre, poteau, duel perdu, faute, carton, ballon perdu, hors-jeu…), sans l'adoucir ni l'embellir. Une tentative absurde est racontée avec le ridicule qu'elle mérite : le public siffle, le capitaine râle. Un but en lucarne mérite une clameur. Pas de chiffre absent des faits, pas de score inventé. Ne renvoie que l'objet JSON.`;
